const modal=document.querySelector('#authModal'),nameField=document.querySelector('#nameField'),modalTitle=document.querySelector('#modalTitle'),modalEyebrow=document.querySelector('#modalEyebrow'),modalText=document.querySelector('#modalText'),submitAuth=document.querySelector('#submitAuth'),switchAuth=document.querySelector('#switchAuth'),toast=document.querySelector('#toast');let mode='login';
function setMode(next){mode=next;const register=mode==='register';nameField.style.display=register?'block':'none';modalEyebrow.textContent=register?'ALĂTURĂ-TE COMUNITĂȚII':'BINE AI REVENIT';modalTitle.innerHTML=register?'Creează cont <span>gratuit</span>':'Intră în <span>NEXUS</span>';modalText.textContent=register?'Profilul tău de gamer este la câteva secunde distanță.':'Conectează-te pentru a continua aventura.';submitAuth.textContent=register?'Creează cont →':'Autentificare →';switchAuth.innerHTML=register?'Ai deja cont? <b>Autentifică-te</b>':'Nu ai cont? <b>Înregistrează-te</b>'}
function openModal(next){setMode(next);modal.classList.add('open');modal.setAttribute('aria-hidden','false');setTimeout(()=>modal.querySelector('input:not([style*="display: none"])')?.focus(),50)}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-modal]').forEach(button=>button.addEventListener('click',()=>openModal(button.dataset.modal)));document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closeModal));switchAuth.addEventListener('click',()=>setMode(mode==='login'?'register':'login'));document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeModal();document.querySelector('#profilePanel').classList.remove('open')}});
document.querySelector('#authForm').addEventListener('submit',event=>{event.preventDefault();closeModal();showToast(mode==='login'?'Autentificare reușită. Bine ai revenit!':'Cont creat. Bun venit în NEXUS!');event.target.reset()});
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
const panel=document.querySelector('#profilePanel');document.querySelector('#profileBtn').addEventListener('click',()=>{panel.classList.add('open');panel.setAttribute('aria-hidden','false')});document.querySelector('#closeProfile').addEventListener('click',()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true')});
document.querySelectorAll('.join-btn').forEach(button=>button.addEventListener('click',()=>{button.textContent='Conectare...';setTimeout(()=>{button.textContent='Intră';showToast('Server pregătit — ne vedem în joc!')},800)}));
document.querySelector('#refreshServers').addEventListener('click',event=>{event.currentTarget.textContent='↻ Se actualizează...';setTimeout(()=>{event.currentTarget.textContent='↻ Actualizează';showToast('Serverele au fost actualizate')},700)});
document.querySelectorAll('.game-card').forEach(card=>card.addEventListener('click',()=>showToast(`${card.dataset.game}: pagina jocului va fi disponibilă în curând`)));
const menu=document.querySelector('.main-nav'),toggle=document.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{menu.classList.toggle('open');toggle.setAttribute('aria-expanded',menu.classList.contains('open'))});document.querySelectorAll('.main-nav a').forEach(link=>link.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
const sections=[...document.querySelectorAll('main section[id]')],links=[...document.querySelectorAll('.main-nav a')];addEventListener('scroll',()=>{const current=sections.slice().reverse().find(section=>scrollY>=section.offsetTop-160);if(current){links.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${current.id}`))}},{passive:true});
